### ISSUE TITLE
[FR] Windows installation path to programm files

### ISSUE THREAD

**Issue by softyoda** [Tw1ddle/geometrize#18]
Hi, it would be nice to have default option for installation to the right place where programm belong usually. This directory shouldn't be used for that. 
![270_explorer_CUsersRYZEN_26_01_2021_13h00(1073x1062)_cGUJ](https://user-images.githubusercontent.com/13988751/105842651-ce142980-5fd6-11eb-945c-d25aaf8ec234.jpg)

**Comment by Tw1ddle** [comment]
Thanks for reporting this, I had a look into it and here's what I found:

 * It's a bit awkward to change the default folder to the correct Program Files folder, because with the 32-bit version of the Qt installer framework I use makes the installer default to "Program Files (x86)", even on 64-bit Windows.

 * Although Windows users expect programs to go in Program Files (x86) or Program Files as this is conventional, these locations require admin rights to install there, which means a UAC prompt is presented that users have to click through. I would rather not the installer require those rights, because the prompt is potentially discouraging/confusing.

 * Installing a program to your user folder isn't unusual, programs are often installed to the hidden %LOCALAPPDATA% folder (C:\Users\yourUsername\AppData\Local).

So, I'll leave the default location as "C:\Users\<YourUsername>". Of course, if you want to customize the installation location, you can change it to something different during the installation process - and the program should still work wherever you install it.
