### ISSUE TITLE
Lack Of Explanation for Shape Data JSON

### ISSUE THREAD

**Issue by OperationOfTheCloud** [Tw1ddle/geometrize#26]
Inside of the shape data json, what does it all mean?

**Comment by Tw1ddle** [comment]
Well the exporter code is here: https://github.com/Tw1ddle/geometrize-lib/blob/d0f652d299e58a9c68e8377c9202b89d474cf580/geometrize/geometrize/exporter/shapejsonexporter.cpp#L19

I should probably have serialized names of shapes instead of id numbers but those are defined here: https://github.com/Tw1ddle/geometrize-lib/blob/d0f652d299e58a9c68e8377c9202b89d474cf580/geometrize/geometrize/shape/shapetypes.h#L16
